---
# tasks file for roles/azure-vmss-web

- name: Generate temp web cloud-init file
  ansible.builtin.tempfile:
  register: tmp_file_create_cloud_init_web_task

- name: Create the web cloud-init file from a template file
  ansible.builtin.template:
    src: "vm-cloud-init-web.yml.j2"
    dest: "{{ tmp_file_create_cloud_init_web_task.path }}"

- name: Create VMSS with an image that requires plan information
  azure.azcollection.azure_rm_virtualmachinescaleset:
    resource_group: "{{ resource_group_name }}"
    name: "{{ vmss_name }}"
    admin_username: "{{ vm_config.admin_username }}"
    admin_password: "{{ vm_password }}"
    ssh_password_enabled: "{{ vm_config.ssh_password_enabled }}"
    vm_size: "{{ vm_config.vm_size }}"
    capacity: "{{ vm_config.vmss.capacity }}"
    virtual_network_name: "{{ virtual_network_name }}"
    subnet_name: "{{ subnet_for_vms }}"
    load_balancer: "{{ load_balancer_name }}"
    upgrade_policy: "{{ vm_config.vmss.upgrade_policy }}"
    custom_data: "{{ lookup('file', '{{ tmp_file_create_cloud_init_web_task.path }}') }}"
    managed_disk_type: "{{ vm_config.disk.managed_disk_type }}"
    image:
      offer: "{{ vm_config.image.offer }}"
      publisher: "{{ vm_config.image.publisher }}"
      sku: "{{ vm_config.image.sku }}"
      version: "{{ vm_config.image.version }}"
    tags: "{{ common_tags }}"
