# Create an azurecaf_name resource, which generates a unique name for an Azure resource of a specified type
resource "azurecaf_name" "resource_group" {
  name          = var.name
  resource_type = "azurerm_resource_group"
  suffixes      = [var.environment_type, module.azure_region.location_short]
  clean_input   = true
}

# Create an azurerm_resource_group resource, which represents an Azure resource group
resource "azurerm_resource_group" "resource_group" {
  # Use the name generated by the azurecaf_name resource as the name of the resource group
  name     = azurecaf_name.resource_group.result
  location = module.azure_region.location_cli
  tags     = var.default_tags
}
