---

- name: Deploy and configure the Azure Environment
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - group_vars/azure.yml
    - group_vars/common.yml

  roles:
    - roles/azure-rg
    - roles/azure-virtualnetwork